ONSdigital/rm-actionexporter-service

Dockerfile

Open port 5141 on docker container for debugging

Docker java debug

---

src/main/resources/database/changes/release-10.49.0/changelog.yml
src/main/resources/database/changes/release-10.49.0/update_initial_print_template.sql

The 'InitialPrint' template needs to be able to write the string 'null' for an iac if it is null. This is the requirement for the downstream system

Update to initial print template

---

pom.xml

Bumping to correct snapshot version as this was missed off from the last release.

Bump version to current snapshot

---

.travis.yml
docker-compose.yml
src/main/resources/database/groundzero.sql
src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java

Enable integration tests to run in travis
* Running `cobertura-integration-test` goal
* Change UID to match travis user id
* Make mounted directory
1. `mvn install`
2. `Travis` has passed
https://trello.com/c/av0gOqFz/149-rm-actionexporter-service-integration-tests-are-not-running-in-travis

Run cobertura integration tests

---

src/main/java/uk/gov/ons/ctp/response/action/ActionExporterApplication.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/Logging.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/ExportMessage.java
src/main/java/uk/gov/ons/ctp/response/action/export/endpoint/TemplateEndpoint.java
src/main/java/uk/gov/ons/ctp/response/action/export/endpoint/TemplateMappingEndpoint.java
src/main/java/uk/gov/ons/ctp/response/action/export/message/ActionFeedbackPublisher.java
src/main/java/uk/gov/ons/ctp/response/action/export/message/EventPublisher.java
src/main/java/uk/gov/ons/ctp/response/action/export/message/SftpServicePublisher.java
src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportScheduler.java
src/main/java/uk/gov/ons/ctp/response/action/export/service/ActionExportService.java
src/main/java/uk/gov/ons/ctp/response/action/export/service/ActionRequestService.java
src/main/java/uk/gov/ons/ctp/response/action/export/service/TemplateMappingService.java
src/main/java/uk/gov/ons/ctp/response/action/export/service/TemplateService.java
src/main/java/uk/gov/ons/ctp/response/action/export/service/TransformationService.java
src/main/java/uk/gov/ons/ctp/response/action/export/templating/freemarker/config/FreeMarkerTemplateLoader.java
src/main/resources/application-cloud.yml
src/main/resources/application.yml
src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java

This PR updates all the logging to use key value pairs from the Godaddy logging package
Updates all logging to use key value pairs.
Run tests
Make sure any log lines haven't been missed

Updating logging to use key value pairs

---

.travis.yml
src/test/java/uk/gov/ons/ctp/response/action/export/service/TransformationServiceImplTest.java

Checking travis build fails with failing test

Fix travis script

---

_infra/Dockerfile
_infra/helm/Chart.yaml
_infra/helm/values.yaml

remveo cpu requests

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/templates/service.yaml
_infra/helm/action-exporter/values.yaml

standardise db config

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

Configurable SFTP volume mount

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/templates/service.yaml
_infra/helm/action-exporter/values.yaml

add managed redis templating

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

add SQL proxy

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

Bring actionexporter config to current preprod

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

Fix config for ftp config

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

SFTP config

---

_infra/helm/action-exporter/templates/deployment.yaml

Fix config missing sftp

---

_infra/helm/action-exporter/templates/deployment.yaml

Quote endpoint enabled config

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

Disable zipkin and add variable to enable

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml

add managedrabbit

---

_infra/helm/action-exporter/values.yaml

The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)

changed service port

---

_infra/helm/action-exporter/templates/deployment.yaml
_infra/helm/action-exporter/values.yaml
src/main/resources/application.yml

Zipkin needed to be removed from the various services.
Removed all mentions of Zipkin.
[Trello card](https://trello.com/c/YZ9aio6I)

removed all mentions of zipkin

---

_infra/helm/action-exporter/templates/deployment.yaml
src/main/java/uk/gov/ons/ctp/response/action/export/message/SftpServicePublisher.java
src/main/resources/application.yml

Increase logging to help diagnose an issue with SFTP

Additional logging and increasing logging level for the SFTP library

---

.github/workflows/main.yml
_infra/helm/action-exporter/Chart.yaml

replace concourse

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/action-exporter/Chart.yaml

Make dev docker tag changes

---

_infra/helm/action-exporter/Chart.yaml
src/main/resources/templates/initialPrint.ftl

Remove white space

---

.github/workflows/main.yml
Dockerfile
_infra/helm/action-exporter/Chart.yaml
pom.xml
src/main/java/uk/gov/ons/ctp/common/error/CTPException.java
src/main/java/uk/gov/ons/ctp/common/error/InvalidRequestException.java
src/main/java/uk/gov/ons/ctp/common/error/RestExceptionHandler.java
src/main/java/uk/gov/ons/ctp/common/message/rabbit/Rabbitmq.java
src/main/java/uk/gov/ons/ctp/common/time/DateTimeUtil.java
src/main/java/uk/gov/ons/ctp/common/util/DeadLetterLogCommand.java
src/main/java/uk/gov/ons/ctp/common/util/InputStreamUtils.java
src/main/java/uk/gov/ons/ctp/common/util/StringToUUIDConverter.java
src/main/java/uk/gov/ons/ctp/response/action/ActionExporterApplication.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/AppConfig.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/DataGrid.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/DataSourceConfiguration.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/ExportSchedule.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/GCS.java
src/main/java/uk/gov/ons/ctp/response/action/export/config/Logging.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/ActionRequestInstruction.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/Address.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/Contact.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/ExportFile.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/ExportJob.java
src/main/java/uk/gov/ons/ctp/response/action/export/domain/TemplateMapping.java
src/main/java/uk/gov/ons/ctp/response/action/export/representation/ActionRequestInstructionDTO.java
src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportInfo.java
src/test/java/uk/gov/ons/tools/rabbit/Rabbitmq.java

The services needed to be upgraded from Java 8 to Java 11.
- Upgraded Java version
- Modified pom.xml dependencies
[Jira card](https://collaborate2.ons.gov.uk/jira/browse/RAS-83)

updated to java 11 and adjusted dependencies

---

_infra/helm/action-exporter/Chart.yaml
_infra/spinnaker/deployment-full.json

syncronize default helm chart

---

.github/workflows/main.yml
_infra/helm/action-exporter/Chart.yaml
_infra/spinnaker/prodDeploy.json

Update needed to hash in production pipeline, to use template with release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141

update SHA in prod template, exclude spinnaker from GH triggers

---

_infra/helm/action-exporter/Chart.yaml
_infra/helm/action-exporter/templates/deployment.yaml

Use the service account created for Kubernetes as this has permission to PUB/SUB and GCS rather than the default service account

Use Kubernetes service account

---

_infra/helm/action-exporter/Chart.yaml
_infra/helm/action-exporter/templates/deployment.yaml

The SFTP volume mount is used by the SFTP test pod and should not be in this helm chart. It's not used by the action exporter.

Remove unnecessary volume and volume mount

---

_infra/helm/action-exporter/Chart.yaml
src/main/resources/actionsvc/xsd/actionInstruction.xsd

XSD needs to be updated after this change to action: https://github.com/ONSdigital/rm-action-service/pull/165

Adding missing element to xsd

---

_infra/helm/action-exporter/Chart.yaml
_infra/helm/action-exporter/templates/deleteCronjob.yaml
_infra/helm/action-exporter/values.yaml

Add feature flag for currently buggy deletion code

---

_infra/helm/action-exporter/Chart.yaml
src/main/java/uk/gov/ons/ctp/response/action/export/endpoint/DeleteEndpoint.java

In the logs it wasn't clear when the process had started and stopped.  This adds some logs to search on.

Add logging for the start and end of the deletion

---

.github/workflows/comment.yml
_infra/helm/action-exporter/Chart.yaml

change from sandbox to dev
