ONSdigital/rm-actionexporter-service

Dockerfile, pom.xml
These changes are driven to allow us to release artifacts in a much simpler way. Currently we have a bunch of shell scripts that we maintain to do releases when this is a core part of maven to be able to bump version, create tags and deploy artifacts.
* Bump versions and remove snapshot 
Release 13 was done on a branch where the version was incremented. The version change hasn't made it's way back into master yet so this change skips that version. We are also removing the snapshot versions.
* Using optional dockerfile buildArgs
We have been fighting with the `COPY target/actionexportersvc*.jar` syntax when
there is  more that one samplesvc*.jar file that  exists in the target
directory. Thought it was fixed by the docker info change but the same
issue occurs when doing a release because …
=> 27 simplify process to create releases of java services

src/main/java/uk/gov/ons/ctp/response/action/export/repository/ActionRequestRepository.java, src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportScheduler.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/ActionRequestService.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/impl/ActionRequestServiceImpl.java
This fixes the query where actionexporter.actionrequest.exercise_ref is in the correct format e.g 201712 and not the 221_201712 format used for BRES.
=> Us012 fixed data

pom.xml
- Changing the actionsvc-api dependency to include `userDescription` for
request instructions.
- Making these changes in a feature branch from tag actionexportersvc-10.49.6 (f0146dee271145d656818f07eb02620b50a0f6d5). This is to avoid deploying actionexportersvc version 10.49.7 in Prod.
- Updating the POM version to `10.49.8-SNAPSHOT`.
- Setting SCM Tag back to `HEAD`.
- Tested this locally.
=> Updating actionsvc-api dependency

manifest.yml
The host will default to the app name. As long as the app name is named
what you want it to be when CF push is ran the host will be the same. As
the manifest file defines the app name it will fallback to that if not
set.
See https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html
=> Remove host from manifest

docker-compose.yml, pom.xml, src/main/java/uk/gov/ons/ctp/response/action/export/config/AppConfig.java, src/main/java/uk/gov/ons/ctp/response/action/export/message/impl/SftpServicePublisherImpl.java, src/main/resources/application-test.yml, src/main/resources/database/changelog-master.yml, src/main/resources/database/changes/release-10.50.0/add_caseref_to_print_template.sql, src/main/resources/database/changes/release-10.50.0/changelog.yml, src/main/resources/database/changes/release-10.50.0/update_template_mapping_for_social.sql, src/main/resources/springintegration/broker.xml, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceImplTest.java, src/test/resources/application-test.properties
This changes adds the template for a social notification letter CSV template and the mapping for social action requests. This enables the action exporter service to generate the CSV files containing the addresses and other details required to generate the social notification letters. These CSV files are sent to an SFTP server to be picked up downstream.
* Added social notification file templates and template mapping rows to the SQL changes and updated changelogs accordingly.
* Added a docker-compose file to start up the services required for an integration test in docker locally. These run with names and ports specific to this service so should not conflict with the containers in [ras-rm-docker-dev](https://github.com/ONSdigital/ras-rm-docker-dev).
* Added an integration test which …
=> Sts008 receive notification letter

src/main/resources/database/changelog-master.yml, src/main/resources/database/changes/release-10.50.1/add_social_pre_notification_template.sql, src/main/resources/database/changes/release-10.50.1/add_social_pre_notification_template_mapping.sql, src/main/resources/database/changes/release-10.50.1/changelog.yml, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
Social surveys have a "Pre Notification" letter that is sent out purely to notify potential respondents before the actual notification which contains their UAC to access the survey online. This PR adds the template for the CSV file containing the address information used to generate these pre notification letters and the template mapping necessary to use this template for `SOCIALPRENOT` action types.
* Add template for social pre notification letter `.csv` files
* Add template mapping for `SOCIALPRENOT` action types
* Add integration test for generation of social pre notification `.csv` file
The new integration test should pass, and after starting the service on this branch you should be able to see the new template and mapping in the database in the `actionexporter` schema in the …
=> Add social pre notification template and mapping

pom.xml, src/main/resources/database/changes/release-10.50.1/changelog.yml, src/main/resources/database/changes/release-10.50.1/use_sample_unit_ref.sql, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
Currently the notifications and pre-notifications for social include caseRef (which looks something like 1000000100010).  This PR changes this to something more business friendly i.e. sampleUnitRef (which looks something like LMS00001).  
- a liquibase script has been added to change the freemarker for the social notifications and pre-notifications
- integration tests have been changed to confirm that result includes sample unit ref not case ref
- updated rm-actionsvc-api dependency version to latest (please note: this will cause travis builds to fail until change is merged)
- check out branch
- run integration tests
- for a more detailed examination run either of the integration tests testTemplateGeneratesCorrectPrintFileForSocial or …
=> A simple PR to change (pre)notifications to include sampleUnitRef instead of caseRef

src/main/java/uk/gov/ons/ctp/response/action/export/domain/Address.java, src/main/resources/database/changelog-master.yml, src/main/resources/database/changes/release-10.51.0/add_lines_3_4_address.sql, src/main/resources/database/changes/release-10.51.0/add_lines_3_4_social_notif_template.sql, src/main/resources/database/changes/release-10.51.0/changelog.yml, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
Lines 3 and 4 were added to the address table and notification file as households typically have lines 3 and 4 in the address.
Two deltas: one adds lines 3 and 4 to the table itself; the other adds lines 3 and 4 to the template which will generate a CSV file on a schedule.
Run all tests in TemplateServiceIT
=> Added address lines 3 and 4 to Address table and notification file

src/main/resources/database/changes/release-10.51.0/add_lines_3_4_social_pre_notif_template.sql, src/main/resources/database/changes/release-10.51.0/changelog.yml, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
Pre notification templates require lines 3 and 4 so that when households first receive an invite to complete the survey it is handed over to the candidate respondent whose address would contain lines 3 and 4 of a valid UK address.
Delta created to add lines 3 and 4 to pre-notification template
Run all tests in TemplateServiceIT
=> Addlines 3 and 4 to pre-notification template

src/main/resources/database/changelog-master.yml, src/main/resources/database/changes/release-10.52.0/add_lines_3_4_social_notif_template.sql, src/main/resources/database/changes/release-10.52.0/add_lines_3_4_social_pre_notif_template.sql, src/main/resources/database/changes/release-10.52.0/changelog.yml, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
The templates need a new line at the end to stop lines all being
on one line. IT tests have been added to check this but ideally we'd
refactor these into unit tests when the templates no longer live in the DB
* Scripts to update the social print file templates with new line characters
* Check the row ends with a newline character in the integration test
Run integration tests
https://trello.com/c/2oPPgbXs/184-add-prem3-and-prem4-to-the-notification-file-5
https://trello.com/c/AAGDVYKL/183-add-prem3-and-prem4-to-pre-notification-template-3
=> Add new line to templates

src/main/resources/database/changelog-master.yml, src/main/resources/database/changes/release-11/add_BSNL_and_BSRL.sql, src/main/resources/database/changes/release-11/changelog.yml
For new environments these currently have to be added manually. In production there are already there so I've added `ON CONFLICT (..) DO NOTHING` to the insert statements.
- New migration file which adds the template mappings
- Moved to a new `release-<single int>` format for the migrations as discussed with @pricem14pc and @madeye-matt 
1. Ensure that `BSNL` and `BSRL` is not present in the `templatemapping` table
1. Start up the service
1. Ensure that the `BSNL` and `BSRL` rows have been added
=> Add BSNL and BSRL template mappings

pom.xml
The Maven dependencies were not organised very logically. There were a couple of dependencies which could be removed. Also, the artifactory repos were missing, which meant that developers had to update their local settings.xml to be able to build the project.
1. Added <profiles> section with "artifactory" profile, after the <parent> section
2. Added comment  at top of <dependencies> section
3. Grouped all the spring dependencies to the top and added comment  at the bottom of the block
4. Removed "spring-boot-starter-jdbc" dependency
5. Removed "javax.servlet-api" dependency
6. Grouped the ONS libraries together with a comment at the top and the bottom
7. Grouped the 3rd party libraries together with a comment at the top and the bottom
8. Grouped the testing libraries together with a …
=> Cleaned up pom.xml

src/main/java/uk/gov/ons/ctp/response/action/export/repository/ActionRequestRepository.java, src/main/java/uk/gov/ons/ctp/response/action/export/repository/AddressRepository.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/impl/ActionExportServiceImpl.java
Improvements team is refactoring all the native Postgres queries which are hard-coded into the repositories, so that JPA is used instead. This should allow us to use Hibernate caching and give us greater stability, because we're not bypassing the persistence framework.
Replaced 2 repository methods with JPA equivalent.
Ran acceptance tests - passing
Trello: https://trello.com/c/bdqQthEj/291-replace-native-postgres-queries-with-jpa-spring-data-queries-in-java-services-l
=> Removed native queries

pom.xml, src/main/java/uk/gov/ons/ctp/response/action/ActionExporterApplication.java, src/main/java/uk/gov/ons/ctp/response/action/export/domain/ExportMessage.java, src/main/java/uk/gov/ons/ctp/response/action/export/endpoint/TemplateEndpoint.java, src/main/java/uk/gov/ons/ctp/response/action/export/endpoint/TemplateMappingEndpoint.java, src/main/java/uk/gov/ons/ctp/response/action/export/message/ActionFeedbackPublisher.java, src/main/java/uk/gov/ons/ctp/response/action/export/message/EventPublisher.java, src/main/java/uk/gov/ons/ctp/response/action/export/message/SftpServicePublisher.java, src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportScheduler.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/ActionExportService.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/ActionRequestService.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/TemplateMappingService.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/TemplateService.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/TransformationService.java, src/main/java/uk/gov/ons/ctp/response/action/export/templating/freemarker/config/FreeMarkerTemplateLoader.java, src/main/resources/logback.xml, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
We've agreed to use the Godaddy logger for structured JSON logging, which we are now rolling out to all the Java services.
Replaced all the `@Slf4j` annotations. Updated the logback.xml config.
Run with CLOUD profile and check that the logs are coming out in the correct JSON format.
Trello: https://trello.com/c/2cLIClJa/348-roll-out-godaddy-logger-to-all-the-other-java-services
Architecture decision: https://github.com/ONSdigital/sdc/blob/master/doc/architecture/decisions/godaddy-structured-json-logging-java.md
=> Roll out Godaddy logger

src/main/resources/springintegration/action-instruction-inbound-flow.xml
This reverts commit 9ec882c6071bb0e199f1505f173be8e1daa98945, reversing
changes made to 91caaaf8483468eb39e4fc1e4cfd081e22ed0222.
payload.actionRequest.contact.emailAddress is not always populated and
can result in infinitely retrying because of a null pointer exception is
thrown with the log being
```
SpelEvaluationException: EL1007E: Property or field 'emailAddress' cannot be found on null
```
Reverting retry strategy
Check logs aren't raising exception when running the acceptance tests
```
2018-08-23T14:42:52.60+0100 [APP/PROC/WEB/0] OUT Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler [ServiceActivator for [org.springframework.integration.handler.MethodInvokingMessageProcessor@6aed7784] …
```
=> Revert "Merge branch 'master' into handle_retries_correctly"

pom.xml, src/main/java/uk/gov/ons/ctp/response/action/ActionExporterApplication.java, src/test/java/uk/gov/ons/ctp/response/action/export/service/TemplateServiceIT.java
Bug discovered by @ajmaddaford in CI-latest where JSON not being used for key-value pairs.
Instead of flipping logging to use JSON in a `CommandLineRunner.run()` method, we're using a `@Postconstruct` instead, which should always fire.
Run with `--spring.profiles.active=cloud` or hack the `application.yml` to set `CLOUD` logger and `useJson=true`
Related Trello card: https://trello.com/c/KNOUa0pq/349-update-logging-in-all-java-services-to-use-key-value-pairs
=> Init JSON logging in PostConstruct method

src/main/java/uk/gov/ons/ctp/response/action/export/service/NotificationFileCreator.java
We are attempting to investigate and fix an intermittent failure of the acceptance tests in CI and Latest, in the pipeline. It was discovered that the file contents have been changing on the FTP server, for the same filename, but further diagnosis has not been possible because the logs were full of lots of "not doing anything" useless log.
Removed useless log line.
Run the actionexporter and check it's not logging "not doing anything" all the time.
Trello: https://trello.com/c/MLoPHcVk/402-bug-check-for-iac-code-in-sftp-file-intermittently-causes-ats-to-fail
=> Remove log line filling up logs with useless info

pom.xml
We recently had to do a bug fix off an earlier release and create a jar from it in artifactory. Because of that we are out of step and the snapshot version needs updating
=> Update snapshot version to 10.49.17

src/main/java/uk/gov/ons/ctp/response/action/export/message/SftpServicePublisher.java, src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportScheduler.java, src/test/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportSchedulerTest.java
Action Exporter was not correctly wired up with Spring Integration to handle SFTP failures. Failures were resulting in exceptions being thrown by Spring, complaining that it couldn't find the error handler method. @davidmort searched the production logs, and thankfully this bug hasn't happened in prod [yet] during the time we've had Splunk, although it's possible that the error wasn't showing up because it wasn't being properly logged - it was spotted in _console output_ by chance.
Changed the method signature of `sftpFailedProcess` so that it matches what the SpEL expression expects to find. Refactored to pull the message headers out of the failed message correctly, so we know which file failed to send via SFTP.
Stop the SFTP server and try running a test which would cause the Action …
=> Fix SFTP failure handling

src/main/resources/application-cloud.yml, src/main/resources/application.yml
This is an out of date module/dependency and it is recommended to use the alternative one in the PR instead.
This mainly provides support for 'if exists' in SQL for database for when we do database transactions/migrations etc.
Updated to use correct dependency
- `mvn clean install` and check if all builds successfully
Card: https://trello.com/c/QwluwHSN/509-upgrade-postgresql-hibernate-dialect-from-deprecated-to-v9-for-all-java-services-s
=> Added undeprecated database platform instead of current one in place

src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportProcessor.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/TemplateMappingService.java, src/main/resources/application-cloud.yml, src/test/java/uk/gov/ons/ctp/response/action/export/scheduled/ExportProcessorTest.java
There's a cron job in Action Exporter with way too much computational complexity and some over the top data structures. This reduces both sets of nested loops to single loops, in one case entirely and in the other by using language features which should make it quicker. I also introduced a new Class to replace a Map of Maps of Lists, which should obviously be much easier to understand and hog less memory.
Refactored how the data was structured to remove nested loops in building the data structure
=> Refactor export algorithm

.gitignore, src/main/resources/database/changes/release-10.40.0/actionexporter_foundation_schema.sql, src/main/resources/database/changes/release-17/changelog.yml, src/main/resources/database/changes/release-17/update_email_field_size.sql, src/test/java/uk/gov/ons/ctp/response/action/export/utility/ActionRequestBuilder.java
The e-mail field in the action exporter schema needed to be changed from 50 to 200 in order to accommodate longer e-mails.
- The `emailaddress` field in `action exporter_foundation_schema.sql` was changed from allowing a maximum of 50 characters to a maximum of 200.
- A line was added into `ActionRequestBuilder.java` to make sure that the tests don't break from having a long e-mail address inserted onto them.
Build the service and make sure everything works.
[Trello card](https://trello.com/c/I75AHija)
=> changed e-mail field character limit

src/main/resources/database/changelog-master.yml, src/main/resources/database/changes/release-10.40.0/actionexporter_foundation_schema.sql, src/main/resources/database/changes/release-17/update_email_field_size.sql, src/test/java/uk/gov/ons/ctp/response/action/export/utility/ActionRequestBuilder.java
Fixing a few minor mistakes in https://github.com/ONSdigital/rm-actionexporter-service/pull/75
1. The master change log was not updated so liquibase would not know to run the update script.
1. The alter table statement was slightly incorrect, for postgres it requires the type keyword
1. The foundation script which originally created the table should not have been modified
=> Fix liquibase script for updating email length

_infra/helm/action-exporter/Chart.yaml, _infra/helm/action-exporter/templates/deployment.yaml, _infra/helm/action-exporter/values.yaml
Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)
=> added if-statement for variable versions

_infra/helm/action-exporter/templates/deployment.yaml, _infra/helm/action-exporter/values.yaml
The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)
=> added devRepo

_infra/helm/action-exporter/Chart.yaml, _infra/helm/action-exporter/templates/deployment.yaml, _infra/helm/action-exporter/values.yaml, pom.xml, src/main/java/uk/gov/ons/ctp/response/action/ActionExporterApplication.java, src/main/java/uk/gov/ons/ctp/response/action/export/config/AppConfig.java, src/main/java/uk/gov/ons/ctp/response/action/export/config/GCS.java, src/main/java/uk/gov/ons/ctp/response/action/export/message/UploadObjectGCS.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/NotificationFileCreator.java, src/main/resources/application-test.yml, src/main/resources/application.yml, src/test/java/uk/gov/ons/ctp/response/action/export/message/UploadObjectGCSTest.java, src/test/java/uk/gov/ons/ctp/response/action/export/service/NotificationFileCreatorTest.java
To Upload the generate sftp file to GCS.
This change will upload the generated file to the gcs bucket making use of the default compute service account, hence appropriate role need to be provided to the service account.
The deployment will also require to provide the updated configuration with the gcs enabled as true and bucket name.
=> Upload SFTP generated file to GCP

_infra/helm/action-exporter/Chart.yaml, src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/DeleteProcessor.java
There was a bug in the deletion where an exportjobId can have actionInstructions with the id but not a corresponding exportfile.  This could be due to manually deleting the exportfile as an example, as in the normal flow of operations, an exportjobid will usually have both 1 or more exportFiles associated with it and 1 or more actionRequestInstructions.
This change checks if that number is 0, and if it is, just deletes all the actionRequestInstructions with that ExportJobId as they won't be used by anything ever again and have essentially been orphaned.
=> Fix delete record bug

_infra/helm/action-exporter/values.yaml, src/main/java/uk/gov/ons/ctp/response/action/export/endpoint/DeleteEndpoint.java, src/main/java/uk/gov/ons/ctp/response/action/export/scheduled/DeleteProcessor.java, src/main/resources/logback.xml, src/test/java/uk/gov/ons/ctp/response/action/export/scheduled/DeleteProcessorTest.java
When deleting a massive amount of records, java was running out of memory.  This should fix it as each exportJob is handled in its own transaction.
Also fixed the duplicate logging by updating the lockback.xml.  It shouldn't have any ill effects, and I've tested the app for a bit and it seems fine but I'm not a logging expert so I can't be sure.
=> Multiple transactions

_infra/helm/action-exporter/Chart.yaml, _infra/helm/action-exporter/templates/deployment.yaml, _infra/helm/action-exporter/values.yaml, src/main/java/uk/gov/ons/ctp/response/action/export/config/AppConfig.java, src/main/java/uk/gov/ons/ctp/response/action/export/config/GCS.java, src/main/java/uk/gov/ons/ctp/response/action/export/message/UploadObjectGCS.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/NotificationFileCreator.java, src/main/java/uk/gov/ons/ctp/response/action/export/service/PrintFileService.java, src/test/java/uk/gov/ons/ctp/response/action/export/service/NotificationFileCreatorTest.java, src/test/java/uk/gov/ons/ctp/response/action/export/service/PrintFileServiceTest.java
Due to the limitation on size for both data store and pubsub the data transfer between action exporter and print file will be done via a GCS bucket.
Action exporter will write the data file to GCS and then publish a message to pubsub with the name of the datafile in it. Print file will then read that file and use the data for templating.
=> Reworking to push to print file data to a gcs bucket
